---
  - name: "Create ec2"
    hosts: localhost
    connection: local   
    gather_facts: false
    tasks:
    - name: Creating ec2 instance
      ec2:
        region: ap-south-1
        key_name: sonarqube
        instance_type: t3a.micro
        image: ami-00782a7608c7fc226
        wait: yes
        wait_timeout: 500
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-099c5c4757d183892
        assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
          host: "{{ item.public_dns_name }}"
          port: 22 
          state: started
      with_items: '{{ ec2.instances }}'


  - name: Configure instance
    hosts: launched
    become: True
    gather_facts: false
    tasks:
      - name: Update and upgrade apt packages
        apt:
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400 #One day
    
      - name: Install Java using Ansible
        apt:
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - openjdk-11-jdk
 
      
       
  
   


  
