---
  - name: Provision an EC2 Instance. 
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisionig
 
    # Task that will be used to Launch/Create an EC2 Instance
    tasks:
        
      - name: Launching  the new EC2 Instance
        ec2:
          instance_type: t2.micro
          security_group: ansible_demo_SG
          image:  ami-0567e0d2b4b2169ae
          keypair: sonarqube
          region: ap-south-1 # Change the Region
          count: 1
          monitoring: no
          vpc_subnet_id: subnet-07760ef71d242791f
          assign_public_ip: yes
        
 
      - name: Add the newly created EC2 instance(s) to the local host group
        local_action: lineinfile 
                      path= demo.txt
                      regexp= {{ item.public_ip }} 
                      insertafter= '\[demo\]' line={{ item.public_ip }}
        with_items: '{{ec2.instances}}'
 
      - name: Add new instance to host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        with_items: "{{ ec2.instances }}"
 
      - name: Let's wait for SSH to come up. Usually that takes ~10 seconds
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: '{{ ec2.instances }}'
 
      
       
  
   


  
