---
- name: Create Ec2 instances
  hosts: localhost
  connection: local
  become: yes
  gather_facts: false
  tasks:
   - name: Creating ec2 instance
     ec2:
       region: ap-south-1
       key_name: sonarqube
       instance_type: t3a.micro
       image:  ami-0567e0d2b4b2169ae
       security group: ansible_demo_SG
       wait: yes
       wait_timeout: 500
       count: 1
       monitoring: no
       vpc_subnet_id: subnet-099c5c4757d183892
       assign_public_ip: yes
       
   - name: Create a security group
     local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for EC2 Servers
          region: "{{ ap-south-1 }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
      register: basic_firewall 
   
       
  
   


  
