---

  - name: Add new instance to host group
    hosts: localhost
    vars_files:
      - ./tf_ansible_vars_file.yml
    tasks:
      - name: Adding host
        add_host:
          hostname: "{{tf_public_ip}}"
          groupname: launched

      - name: Wait for SSH to come up
        wait_for:
            host: "{{tf_public_dns_name}}"
            port: 22 
            state: started



  - name: Configure instance
    hosts: launched
    become: True
    gather_facts: false
    tasks:
      - name: Copy the jar file from slave instance to new instance
        become: true 
        copy:
          src: ./target/myapp-1.0.jar
          dest: /home/ubuntu/


      - name: Update apt packages
        apt:
          update_cache: yes
          cache_valid_time: 86400 #One day
    
      - name: Installing jdk 11
        apt:
          update_cache: yes
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - openjdk-11-jdk-headless

      - name: Deploy java 
        shell: nohup java -jar myapp-1.0.jar &
      
       
  
   


  
