---
  - name: Provision an EC2 Instance. 
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning
    # required parameters
    vars:
      instance_type: t2.micro
      security_group: ansible_demo_SG
      image:  ami-0567e0d2b4b2169ae
      keypair: sonarqube
      region: ap-south-1 # Change the Region
      count: 1
 
    # Task that will be used to Launch/Create an EC2 Instance
    tasks:
 
      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          state: absent
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall
        
      - name: Launching  the new EC2 Instance
        local_action: ec2 
                      group= {{ security_group }} 
                      instance_type= {{ instance_type}} 
                      image= {{ image }} 
                      wait= true
                      wait_timeout= 500 
                      region= {{ region }} 
                      keypair= {{ keypair }}
                      count= 1
        register: ec2_instance
 
      - name: Add the newly created EC2 instance(s) to the local host group
        local_action: lineinfile 
                      path= demo.txt
                      regexp= {{ item.public_ip }} 
                      insertafter= '\[demo\]' line={{ item.public_ip }}
        with_items: '{{ec2.instances}}'
 
      - name: Add new instance to host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        with_items: "{{ ec2.instances }}"
 
      - name: Let's wait for SSH to come up. Usually that takes ~10 seconds
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: '{{ ec2.instances }}'
 
      
       
  
   


  
