---
  - name: "Create ec2"
    hosts: localhost
    connection: local   
    gather_facts: false
    tasks:
    - name: Creating ec2 instance
      ec2:
        region: ap-south-1
        key_name: sonarqube
        instance_type: t3a.micro
        image: ami-0567e0d2b4b2169ae
        wait: yes
        wait_timeout: 500
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-099c5c4757d183892
        assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
          host: "{{ item.public_dns_name }}"
          port: 22 
          state: started
      with_items: '{{ ec2.instances }}'



  - name: Configure instance
    hosts: launched
    become: True
    gather_facts: false
    tasks:
      - name: Copy the jar file from slave instance to new instance
        become: true 
        copy:
          src: /home/ubuntu/ansible-demo/target/myapp-1.0.jar
          dest: /home/ubuntu/


      - name: Update apt packages
        apt:
          update_cache: yes
          cache_valid_time: 86400 #One day
    
      - name: Installing jdk 11
        apt:
          update_cache: yes
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - openjdk-11-jdk

      - name: Deploy java 
        shell: nohup java -jar myapp-1.0.jar &
      
       
  
   


  
